<a href="https://colab.research.google.com/github/kaushal4445/AI-ML/blob/main/fetch_data_from_API.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Fetch Data from API**

In [2]:
import pandas as pd
import requests

## **Taking requets from AI**

In [5]:
response = requests.get('https://api.themoviedb.org/3/tv/top_rated?api_key=9b473644c9294c3a7186c778c83440c7&language=en-US&page=1')

In [6]:
response.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/vyG93jhmPL7tBIhRtCLa5mdBKob.jpg',
   'genre_ids': [10759, 18, 35],
   'id': 276161,
   'origin_country': ['KR'],
   'original_language': 'ko',
   'original_name': '참교육',
   'overview': "When respect collapses in schools, unconventional inspectors arrive to set things right — with sharp, no-nonsense lessons you won't find in textbooks.",
   'popularity': 295.0964,
   'poster_path': '/fMECSPrTmRClSViMsXFYmiYIcWP.jpg',
   'first_air_date': '2026-06-05',
   'softcore': False,
   'name': 'Teach You a Lesson',
   'vote_average': 9.445,
   'vote_count': 292},
  {'adult': False,
   'backdrop_path': '/wh5agdl3b7fqC7mSjsCkHx4fMAs.jpg',
   'genre_ids': [37, 18],
   'id': 299167,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Dutton Ranch',
   'overview': 'Rip Wheeler and Beth Dutton gamble everything on a new life in South Texas, but the promise of building a future far from the ghosts of Yellowstone quickly collides with brutal new realities and a rival ranch that will stop at nothing to protect its empire.',
   'popularity': 162.7442,
   'poster_path': '/xsiecCxd8lkcAluw0wWwbW5CwSv.jpg',
   'first_air_date': '2026-05-15',
   'softcore': False,
   'name': 'Dutton Ranch',
   'vote_average': 9.4,
   'vote_count': 268},
  {'adult': False,
   'backdrop_path': '/52sp0vPhLOWrZ1QoZIWiapronM.jpg',
   'genre_ids': [18],
   'id': 273240,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Off Campus',
   'overview': 'Hannah Wells tutors hockey captain Garrett Graham to win over her crush. Their deal becomes real connection as they face their pasts. Friends Logan, Dean, Tucker, and Allie navigate college life and love.',
   'popularity': 359.1916,
   'poster_path': '/cbODFqkcmRgrYH8NkG4Q4Hcg8Z1.jpg',
   'first_air_date': '2026-05-13',
   'softcore': False,
   'name': 'Off Campus',
   'vote_average': 8.99,
   'vote_count': 456},
  {'adult': False,
   'backdrop_path': '/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
   'genre_ids': [18, 80],
   'id': 1396,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Breaking Bad',
   'overview': "Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
   'popularity': 140.8924,
   'poster_path': '/3xnWaLQjelJDDF7LT1WBo6f4BRe.jpg',
   'first_air_date': '2008-01-20',
   'softcore': False,
   'name': 'Breaking Bad',
   'vote_average': 8.947,
   'vote_count': 17922},
  {'adult': False,
   'backdrop_path': '/rBOnrVlck7BIlGeWVlzYiZeg4l2.jpg',
   'genre_ids': [16, 10759, 18, 10765],
   'id': 209867,
   'origin_country': ['JP'],
   'original_language': 'ja',
   'original_name': '葬送のフリーレン',
   'overview': 'After the party of heroes defeated the Demon King, they restored peace to the land and returned to lives of solitude.  Generations pass, and the elven mage Frieren comes face to face with humanity’s mortality. She takes on a new apprentice and promises to fulfill old friends’ dying wishes. Can an elven mind make peace with the nature of life and death? Frieren embarks on her quest to find out.',
   'popularity': 68.8367,
   'poster_path': '/dqZENchTd7lp5zht7BdlqM7RBhD.jpg',
   'first_air_date': '2023-09-29',
   'softcore': False,
   'name': "Frieren: Beyond Journey's End",
   'vote_average': 8.803,
   'vote_count': 847},
  {'adult': False,
   'backdrop_path': '/sZH7lGs06skRKkrqp1LRi57VVMb.jpg',
   'genre_ids': [35],
   'id': 64010,
   'origin_country': ['KR'],
   'original_language': 'ko',
   'original_name': '응답하라 1988',
   'overview': 'Take a nostalgic trip back to the late 1980s through the lives of five families and their five teenage kids living in a small neighbourhood in Seoul.',
   'popularity': 14.4941,
   'poster_path': '/i3xQJlQRff4k5IMEY55l4iKaKl3.jpg',
   'first_air_date': '2015-11-06',
   'softcore': False,
   'name': 'Reply 1988',
   'vote_average': 8.759,
   'vote_count': 214},
  {'adult': False,
   'backdrop_path': '/7oBGhqJIghRBvOwo5Qe0yM0cnMc.jpg',
   'genre_ids': [16, 10759, 10765],
   'id': 246,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Avatar: The Last Airbender',
   'overview': 'In a war-torn world of elemental magic, a young boy reawakens to undertake a dangerous mystic quest to fulfill his destiny as the Avatar, and bring peace to the world.',
   'popularity': 21.6832,
   'poster_path': '/9RQhVb3r3mCMqYVhLoCu4EvuipP.jpg',
   'first_air_date': '2005-02-21',
   'softcore': False,
   'name': 'Avatar: The Last Airbender',
   'vote_average': 8.8,
   'vote_count': 4873},
  {'adult': False,
   'backdrop_path': '/q8eejQcg1bAqImEV8jh8RtBD4uH.jpg',
   'genre_ids': [16, 10759, 10765],
   'id': 94605,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Arcane',
   'overview': 'Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.',
   'popularity': 31.3915,
   'poster_path': '/abf8tHznhSvl9BAElD2cQeRr7do.jpg',
   'first_air_date': '2021-11-06',
   'softcore': False,
   'name': 'Arcane',
   'vote_average': 8.752,
   'vote_count': 5934},
  {'adult': False,
   'backdrop_path': '/7Sgo1XdCrIpJpiNsTPMi9vwKSuC.jpg',
   'genre_ids': [18],
   'id': 250307,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'The Pitt',
   'overview': "The staff of Pittsburgh's Trauma Medical Center work around the clock to save lives in an overcrowded and underfunded emergency department.",
   'popularity': 53.3731,
   'poster_path': '/kvFSpESyBZMjaeOJDx7RS3P1jey.jpg',
   'first_air_date': '2025-01-09',
   'softcore': False,
   'name': 'The Pitt',
   'vote_average': 8.744,
   'vote_count': 782},
  {'adult': False,
   'backdrop_path': '/mwczMJeoQrsPERcyP1e900jo3Jv.jpg',
   'genre_ids': [18],
   'id': 219246,
   'origin_country': ['KR'],
   'original_language': 'ko',
   'original_name': '폭싹 속았수다',
   'overview': "In Jeju, a spirited girl and a steadfast boy's island story blossoms into a lifelong tale of setbacks and triumphs — proving love endures across time.",
   'popularity': 26.4692,
   'poster_path': '/1VC3sEFxYXYDqQUCAnvWfUsYg1s.jpg',
   'first_air_date': '2025-03-07',
   'softcore': False,
   'name': 'When Life Gives You Tangerines',
   'vote_average': 8.7,
   'vote_count': 534},
  {'adult': False,
   'backdrop_path': '/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg',
   'genre_ids': [10759, 35, 16],
   'id': 37854,
   'origin_country': ['JP'],
   'original_language': 'ja',
   'original_name': 'ワンピース',
   'overview': 'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
   'popularity': 46.6875,
   'poster_path': '/dB4EDhre2dsC2kxYDavyKWqLQwi.jpg',
   'first_air_date': '1999-10-20',
   'softcore': False,
   'name': 'One Piece',
   'vote_average': 8.738,
   'vote_count': 5350},
  {'adult': False,
   'backdrop_path': '/3siv3RaQrdr2tQiv9jHq71sLlzo.jpg',
   'genre_ids': [10759, 10751, 18],
   'id': 85077,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'The Chosen',
   'overview': 'The life of Christ through the eyes of those who encountered him.',
   'popularity': 41.5845,
   'poster_path': '/dqVUFuNrMFWt7uGNWlpo91VKYOI.jpg',
   'first_air_date': '2019-04-21',
   'softcore': False,
   'name': 'The Chosen',
   'vote_average': 8.738,
   'vote_count': 894},
  {'adult': False,
   'backdrop_path': '/QbRbCULZVBcrN2uydpmIOQLV5O.jpg',
   'genre_ids': [18],
   'id': 301507,
   'origin_country': ['CA'],
   'original_language': 'en',
   'original_name': 'Heated Rivalry',
   'overview': 'Two of the biggest stars in Major League Hockey are bound by ambition, rivalry, and a magnetic pull neither of them fully understands. What begins as a secret fling between two fresh faced rookies evolves into a years-long journey of love, denial, and self-discovery. Over the next eight years, as they chase glory on the ice, they struggle to navigate their feelings for each other. Torn between the sport they live for and the love they can’t ignore, they must decide if there’s room in their fiercely competitive world for something as fragile – and powerful – as real love.',
   'popularity': 19.7786,
   'poster_path': '/3YCKbtAkYWCMDLHvkUjGhG7eWoS.jpg',
   'first_air_date': '2025-11-28',
   'softcore': False,
   'name': 'Heated Rivalry',
   'vote_average': 8.729,
   'vote_count': 504},
  {'adult': False,
   'backdrop_path': '/3URK0z9PzpVNJrGE7XOuyy6KFzk.jpg',
   'genre_ids': [18],
   'id': 87108,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Chernobyl',
   'overview': 'The true story of one of the worst man-made catastrophes in history: the catastrophic nuclear accident at Chernobyl. A tale of the brave men and women who sacrificed to save Europe from unimaginable disaster.',
   'popularity': 26.4686,
   'poster_path': '/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg',
   'first_air_date': '2019-05-06',
   'softcore': False,
   'name': 'Chernobyl',
   'vote_average': 8.714,
   'vote_count': 7931},
  {'adult': False,
   'backdrop_path': '/2UG177tWHy7xRmMKWJHB7nAUmKd.jpg',
   'genre_ids': [16, 10759, 10765, 18],
   'id': 31911,
   'origin_country': ['JP'],
   'original_language': 'ja',
   'original_name': '鋼の錬金術師 FULLMETAL ALCHEMIST',
   'overview': 'Disregard for alchemy’s laws ripped half of Edward Elric’s limbs from his body and left his brother Alphonse’s soul clinging to a suit of armor. To restore what was lost, the brothers seek the Philosopher’s Stone. Enemies and allies – the corrupt military, the Homunculi, and foreign alchemists – will alter the Elric brothers course, but their purpose will remain unchanged and their bond unbreakable.',
   'popularity': 45.4275,
   'poster_path': '/5ZFUEOULaVml7pQuXxhpR2SmVUw.jpg',
   'first_air_date': '2009-04-05',
   'softcore': False,
   'name': 'Fullmetal Alchemist: Brotherhood',
   'vote_average': 8.71,
   'vote_count': 2469},
  {'adult': False,
   'backdrop_path': '/og2jKploGHYnCz68vV1nRSEE0xV.jpg',
   'genre_ids': [80, 18],
   'id': 60059,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Better Call Saul',
   'overview': 'Six years before Saul Goodman meets Walter White. We meet him when the man who will become Saul Goodman is known as Jimmy McGill, a small-time lawyer searching for his destiny, and, more immediately, hustling to make ends meet. Working alongside, and, often, against Jimmy, is “fixer” Mike Ehrmantraut. The series tracks Jimmy’s transformation into Saul Goodman, the man who puts “criminal” in “criminal lawyer".',
   'popularity': 81.0712,
   'poster_path': '/zjg4jpK1Wp2kiRvtt5ND0kznako.jpg',
   'first_air_date': '2015-02-08',
   'softcore': False,
   'name': 'Better Call Saul',
   'vote_average': 8.7,
   'vote_count': 6538},
  {'adult': False,
   'backdrop_path': '/q5mJ4oKfGc6Cr9reIHFzD0pQzre.jpg',
   'genre_ids': [10759, 18],
   'id': 200709,
   'origin_country': ['KR'],
   'original_language': 'ko',
   'original_name': '약한영웅',
   'overview': 'With the aid of unexpected friends, a gifted but introverted student confronts bullies and violent foes — unaware of how dangerous his world will become.',
   'popularity': 82.823,
   'poster_path': '/5Sd01WeraL2oA3Vv6O4rcRxockn.jpg',
   'first_air_date': '2022-11-18',
   'softcore': False,
   'name': 'Weak Hero',
   'vote_average': 8.699,
   'vote_count': 448},
  {'adult': False,
   'backdrop_path': '/9In9QgVJx7PlFOAgVHCKKSbo605.jpg',
   'genre_ids': [16, 35, 10765, 10759],
   'id': 60625,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Rick and Morty',
   'overview': 'Follows a sociopathic genius scientist who drags his inherently timid grandson on adventures across the universe.',
   'popularity': 162.705,
   'poster_path': '/owhkU6KRqdXoUQpjV8uyZGPtX58.jpg',
   'first_air_date': '2013-12-02',
   'softcore': False,
   'name': 'Rick and Morty',
   'vote_average': 8.7,
   'vote_count': 10974},
  {'adult': False,
   'backdrop_path': '/rqbCbjB19amtOtFQbb3K2lgm2zv.jpg',
   'genre_ids': [16, 10765, 10759],
   'id': 1429,
   'origin_country': ['JP'],
   'original_language': 'ja',
   'original_name': '進撃の巨人',
   'overview': '100 years ago, the last remnants of humanity were forced to retreat behind the towering walls of a fortified city to escape the massive, man-eating Titans that roamed the land outside their fortress. Only the members of the Scouting Legion dared to stray beyond the safety of the walls – but even those brave warriors seldom returned alive. Those within the city clung to the illusion of a peaceful existence until the day that dream was shattered, and their slim chance at survival was reduced to one horrifying choice: kill – or be devoured!',
   'popularity': 36.6622,
   'poster_path': '/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg',
   'first_air_date': '2013-04-07',
   'softcore': False,
   'name': 'Attack on Titan',
   'vote_average': 8.7,
   'vote_count': 7449},
  {'adult': False,
   'backdrop_path': '/lNpkvX2s8LGB0mjGODMT4o6Up7j.jpg',
   'genre_ids': [80, 18],
   'id': 1398,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'The Sopranos',
   'overview': "The story of New Jersey-based Italian-American mobster Tony Soprano and the difficulties he faces as he tries to balance the conflicting requirements of his home life and the criminal organization he heads. Those difficulties are often highlighted through his ongoing professional relationship with psychiatrist Jennifer Melfi. The show features Tony's family members and Mafia associates in prominent roles and story arcs, most notably his wife Carmela and his cousin and protégé Christopher Moltisanti.",
   'popularity': 83.5159,
   'poster_path': '/rTc7ZXdroqjkKivFPvCPX0Ru7uw.jpg',
   'first_air_date': '1999-01-10',
   'softcore': False,
   'name': 'The Sopranos',
   'vote_average': 8.7,
   'vote_count': 3489}],
 'total_pages': 123,
 'total_results': 2460}

In [7]:
response.json()['results']

[{'adult': False,
  'backdrop_path': '/vyG93jhmPL7tBIhRtCLa5mdBKob.jpg',
  'genre_ids': [10759, 18, 35],
  'id': 276161,
  'origin_country': ['KR'],
  'original_language': 'ko',
  'original_name': '참교육',
  'overview': "When respect collapses in schools, unconventional inspectors arrive to set things right — with sharp, no-nonsense lessons you won't find in textbooks.",
  'popularity': 295.0964,
  'poster_path': '/fMECSPrTmRClSViMsXFYmiYIcWP.jpg',
  'first_air_date': '2026-06-05',
  'softcore': False,
  'name': 'Teach You a Lesson',
  'vote_average': 9.445,
  'vote_count': 292},
 {'adult': False,
  'backdrop_path': '/wh5agdl3b7fqC7mSjsCkHx4fMAs.jpg',
  'genre_ids': [37, 18],
  'id': 299167,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Dutton Ranch',
  'overview': 'Rip Wheeler and Beth Dutton gamble everything on a new life in South Texas, but the promise of building a future far from the ghosts of Yellowstone quickly collides with brutal new realities and a rival ranch that will stop at nothing to protect its empire.',
  'popularity': 162.7442,
  'poster_path': '/xsiecCxd8lkcAluw0wWwbW5CwSv.jpg',
  'first_air_date': '2026-05-15',
  'softcore': False,
  'name': 'Dutton Ranch',
  'vote_average': 9.4,
  'vote_count': 268},
 {'adult': False,
  'backdrop_path': '/52sp0vPhLOWrZ1QoZIWiapronM.jpg',
  'genre_ids': [18],
  'id': 273240,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Off Campus',
  'overview': 'Hannah Wells tutors hockey captain Garrett Graham to win over her crush. Their deal becomes real connection as they face their pasts. Friends Logan, Dean, Tucker, and Allie navigate college life and love.',
  'popularity': 359.1916,
  'poster_path': '/cbODFqkcmRgrYH8NkG4Q4Hcg8Z1.jpg',
  'first_air_date': '2026-05-13',
  'softcore': False,
  'name': 'Off Campus',
  'vote_average': 8.99,
  'vote_count': 456},
 {'adult': False,
  'backdrop_path': '/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
  'genre_ids': [18, 80],
  'id': 1396,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Breaking Bad',
  'overview': "Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
  'popularity': 140.8924,
  'poster_path': '/3xnWaLQjelJDDF7LT1WBo6f4BRe.jpg',
  'first_air_date': '2008-01-20',
  'softcore': False,
  'name': 'Breaking Bad',
  'vote_average': 8.947,
  'vote_count': 17922},
 {'adult': False,
  'backdrop_path': '/rBOnrVlck7BIlGeWVlzYiZeg4l2.jpg',
  'genre_ids': [16, 10759, 18, 10765],
  'id': 209867,
  'origin_country': ['JP'],
  'original_language': 'ja',
  'original_name': '葬送のフリーレン',
  'overview': 'After the party of heroes defeated the Demon King, they restored peace to the land and returned to lives of solitude.  Generations pass, and the elven mage Frieren comes face to face with humanity’s mortality. She takes on a new apprentice and promises to fulfill old friends’ dying wishes. Can an elven mind make peace with the nature of life and death? Frieren embarks on her quest to find out.',
  'popularity': 68.8367,
  'poster_path': '/dqZENchTd7lp5zht7BdlqM7RBhD.jpg',
  'first_air_date': '2023-09-29',
  'softcore': False,
  'name': "Frieren: Beyond Journey's End",
  'vote_average': 8.803,
  'vote_count': 847},
 {'adult': False,
  'backdrop_path': '/sZH7lGs06skRKkrqp1LRi57VVMb.jpg',
  'genre_ids': [35],
  'id': 64010,
  'origin_country': ['KR'],
  'original_language': 'ko',
  'original_name': '응답하라 1988',
  'overview': 'Take a nostalgic trip back to the late 1980s through the lives of five families and their five teenage kids living in a small neighbourhood in Seoul.',
  'popularity': 14.4941,
  'poster_path': '/i3xQJlQRff4k5IMEY55l4iKaKl3.jpg',
  'first_air_date': '2015-11-06',
  'softcore': False,
  'name': 'Reply 1988',
  'vote_average': 8.759,
  'vote_count': 214},
 {'adult': False,
  'backdrop_path': '/7oBGhqJIghRBvOwo5Qe0yM0cnMc.jpg',
  'genre_ids': [16, 10759, 10765],
  'id': 246,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Avatar: The Last Airbender',
  'overview': 'In a war-torn world of elemental magic, a young boy reawakens to undertake a dangerous mystic quest to fulfill his destiny as the Avatar, and bring peace to the world.',
  'popularity': 21.6832,
  'poster_path': '/9RQhVb3r3mCMqYVhLoCu4EvuipP.jpg',
  'first_air_date': '2005-02-21',
  'softcore': False,
  'name': 'Avatar: The Last Airbender',
  'vote_average': 8.8,
  'vote_count': 4873},
 {'adult': False,
  'backdrop_path': '/q8eejQcg1bAqImEV8jh8RtBD4uH.jpg',
  'genre_ids': [16, 10759, 10765],
  'id': 94605,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Arcane',
  'overview': 'Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.',
  'popularity': 31.3915,
  'poster_path': '/abf8tHznhSvl9BAElD2cQeRr7do.jpg',
  'first_air_date': '2021-11-06',
  'softcore': False,
  'name': 'Arcane',
  'vote_average': 8.752,
  'vote_count': 5934},
 {'adult': False,
  'backdrop_path': '/7Sgo1XdCrIpJpiNsTPMi9vwKSuC.jpg',
  'genre_ids': [18],
  'id': 250307,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'The Pitt',
  'overview': "The staff of Pittsburgh's Trauma Medical Center work around the clock to save lives in an overcrowded and underfunded emergency department.",
  'popularity': 53.3731,
  'poster_path': '/kvFSpESyBZMjaeOJDx7RS3P1jey.jpg',
  'first_air_date': '2025-01-09',
  'softcore': False,
  'name': 'The Pitt',
  'vote_average': 8.744,
  'vote_count': 782},
 {'adult': False,
  'backdrop_path': '/mwczMJeoQrsPERcyP1e900jo3Jv.jpg',
  'genre_ids': [18],
  'id': 219246,
  'origin_country': ['KR'],
  'original_language': 'ko',
  'original_name': '폭싹 속았수다',
  'overview': "In Jeju, a spirited girl and a steadfast boy's island story blossoms into a lifelong tale of setbacks and triumphs — proving love endures across time.",
  'popularity': 26.4692,
  'poster_path': '/1VC3sEFxYXYDqQUCAnvWfUsYg1s.jpg',
  'first_air_date': '2025-03-07',
  'softcore': False,
  'name': 'When Life Gives You Tangerines',
  'vote_average': 8.7,
  'vote_count': 534},
 {'adult': False,
  'backdrop_path': '/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg',
  'genre_ids': [10759, 35, 16],
  'id': 37854,
  'origin_country': ['JP'],
  'original_language': 'ja',
  'original_name': 'ワンピース',
  'overview': 'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
  'popularity': 46.6875,
  'poster_path': '/dB4EDhre2dsC2kxYDavyKWqLQwi.jpg',
  'first_air_date': '1999-10-20',
  'softcore': False,
  'name': 'One Piece',
  'vote_average': 8.738,
  'vote_count': 5350},
 {'adult': False,
  'backdrop_path': '/3siv3RaQrdr2tQiv9jHq71sLlzo.jpg',
  'genre_ids': [10759, 10751, 18],
  'id': 85077,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'The Chosen',
  'overview': 'The life of Christ through the eyes of those who encountered him.',
  'popularity': 41.5845,
  'poster_path': '/dqVUFuNrMFWt7uGNWlpo91VKYOI.jpg',
  'first_air_date': '2019-04-21',
  'softcore': False,
  'name': 'The Chosen',
  'vote_average': 8.738,
  'vote_count': 894},
 {'adult': False,
  'backdrop_path': '/QbRbCULZVBcrN2uydpmIOQLV5O.jpg',
  'genre_ids': [18],
  'id': 301507,
  'origin_country': ['CA'],
  'original_language': 'en',
  'original_name': 'Heated Rivalry',
  'overview': 'Two of the biggest stars in Major League Hockey are bound by ambition, rivalry, and a magnetic pull neither of them fully understands. What begins as a secret fling between two fresh faced rookies evolves into a years-long journey of love, denial, and self-discovery. Over the next eight years, as they chase glory on the ice, they struggle to navigate their feelings for each other. Torn between the sport they live for and the love they can’t ignore, they must decide if there’s room in their fiercely competitive world for something as fragile – and powerful – as real love.',
  'popularity': 19.7786,
  'poster_path': '/3YCKbtAkYWCMDLHvkUjGhG7eWoS.jpg',
  'first_air_date': '2025-11-28',
  'softcore': False,
  'name': 'Heated Rivalry',
  'vote_average': 8.729,
  'vote_count': 504},
 {'adult': False,
  'backdrop_path': '/3URK0z9PzpVNJrGE7XOuyy6KFzk.jpg',
  'genre_ids': [18],
  'id': 87108,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Chernobyl',
  'overview': 'The true story of one of the worst man-made catastrophes in history: the catastrophic nuclear accident at Chernobyl. A tale of the brave men and women who sacrificed to save Europe from unimaginable disaster.',
  'popularity': 26.4686,
  'poster_path': '/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg',
  'first_air_date': '2019-05-06',
  'softcore': False,
  'name': 'Chernobyl',
  'vote_average': 8.714,
  'vote_count': 7931},
 {'adult': False,
  'backdrop_path': '/2UG177tWHy7xRmMKWJHB7nAUmKd.jpg',
  'genre_ids': [16, 10759, 10765, 18],
  'id': 31911,
  'origin_country': ['JP'],
  'original_language': 'ja',
  'original_name': '鋼の錬金術師 FULLMETAL ALCHEMIST',
  'overview': 'Disregard for alchemy’s laws ripped half of Edward Elric’s limbs from his body and left his brother Alphonse’s soul clinging to a suit of armor. To restore what was lost, the brothers seek the Philosopher’s Stone. Enemies and allies – the corrupt military, the Homunculi, and foreign alchemists – will alter the Elric brothers course, but their purpose will remain unchanged and their bond unbreakable.',
  'popularity': 45.4275,
  'poster_path': '/5ZFUEOULaVml7pQuXxhpR2SmVUw.jpg',
  'first_air_date': '2009-04-05',
  'softcore': False,
  'name': 'Fullmetal Alchemist: Brotherhood',
  'vote_average': 8.71,
  'vote_count': 2469},
 {'adult': False,
  'backdrop_path': '/og2jKploGHYnCz68vV1nRSEE0xV.jpg',
  'genre_ids': [80, 18],
  'id': 60059,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Better Call Saul',
  'overview': 'Six years before Saul Goodman meets Walter White. We meet him when the man who will become Saul Goodman is known as Jimmy McGill, a small-time lawyer searching for his destiny, and, more immediately, hustling to make ends meet. Working alongside, and, often, against Jimmy, is “fixer” Mike Ehrmantraut. The series tracks Jimmy’s transformation into Saul Goodman, the man who puts “criminal” in “criminal lawyer".',
  'popularity': 81.0712,
  'poster_path': '/zjg4jpK1Wp2kiRvtt5ND0kznako.jpg',
  'first_air_date': '2015-02-08',
  'softcore': False,
  'name': 'Better Call Saul',
  'vote_average': 8.7,
  'vote_count': 6538},
 {'adult': False,
  'backdrop_path': '/q5mJ4oKfGc6Cr9reIHFzD0pQzre.jpg',
  'genre_ids': [10759, 18],
  'id': 200709,
  'origin_country': ['KR'],
  'original_language': 'ko',
  'original_name': '약한영웅',
  'overview': 'With the aid of unexpected friends, a gifted but introverted student confronts bullies and violent foes — unaware of how dangerous his world will become.',
  'popularity': 82.823,
  'poster_path': '/5Sd01WeraL2oA3Vv6O4rcRxockn.jpg',
  'first_air_date': '2022-11-18',
  'softcore': False,
  'name': 'Weak Hero',
  'vote_average': 8.699,
  'vote_count': 448},
 {'adult': False,
  'backdrop_path': '/9In9QgVJx7PlFOAgVHCKKSbo605.jpg',
  'genre_ids': [16, 35, 10765, 10759],
  'id': 60625,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Rick and Morty',
  'overview': 'Follows a sociopathic genius scientist who drags his inherently timid grandson on adventures across the universe.',
  'popularity': 162.705,
  'poster_path': '/owhkU6KRqdXoUQpjV8uyZGPtX58.jpg',
  'first_air_date': '2013-12-02',
  'softcore': False,
  'name': 'Rick and Morty',
  'vote_average': 8.7,
  'vote_count': 10974},
 {'adult': False,
  'backdrop_path': '/rqbCbjB19amtOtFQbb3K2lgm2zv.jpg',
  'genre_ids': [16, 10765, 10759],
  'id': 1429,
  'origin_country': ['JP'],
  'original_language': 'ja',
  'original_name': '進撃の巨人',
  'overview': '100 years ago, the last remnants of humanity were forced to retreat behind the towering walls of a fortified city to escape the massive, man-eating Titans that roamed the land outside their fortress. Only the members of the Scouting Legion dared to stray beyond the safety of the walls – but even those brave warriors seldom returned alive. Those within the city clung to the illusion of a peaceful existence until the day that dream was shattered, and their slim chance at survival was reduced to one horrifying choice: kill – or be devoured!',
  'popularity': 36.6622,
  'poster_path': '/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg',
  'first_air_date': '2013-04-07',
  'softcore': False,
  'name': 'Attack on Titan',
  'vote_average': 8.7,
  'vote_count': 7449},
 {'adult': False,
  'backdrop_path': '/lNpkvX2s8LGB0mjGODMT4o6Up7j.jpg',
  'genre_ids': [80, 18],
  'id': 1398,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'The Sopranos',
  'overview': "The story of New Jersey-based Italian-American mobster Tony Soprano and the difficulties he faces as he tries to balance the conflicting requirements of his home life and the criminal organization he heads. Those difficulties are often highlighted through his ongoing professional relationship with psychiatrist Jennifer Melfi. The show features Tony's family members and Mafia associates in prominent roles and story arcs, most notably his wife Carmela and his cousin and protégé Christopher Moltisanti.",
  'popularity': 83.5159,
  'poster_path': '/rTc7ZXdroqjkKivFPvCPX0Ru7uw.jpg',
  'first_air_date': '1999-01-10',
  'softcore': False,
  'name': 'The Sopranos',
  'vote_average': 8.7,
  'vote_count': 3489}]

In [8]:
pd.DataFrame(response.json()['results'])

,adult,backdrop_path,genre_ids,id,origin_country,original_language,original_name,overview,popularity,poster_path,first_air_date,softcore,name,vote_average,vote_count
0,False,/vyG93jhmPL7tBIhRtCLa5mdBKob.jpg,"[10759, 18, 35]",276161,[KR],ko,참교육,"When respect collapses in schools, unconventio...",295.0964,/fMECSPrTmRClSViMsXFYmiYIcWP.jpg,2026-06-05,False,Teach You a Lesson,9.445,292
1,False,/wh5agdl3b7fqC7mSjsCkHx4fMAs.jpg,"[37, 18]",299167,[US],en,Dutton Ranch,Rip Wheeler and Beth Dutton gamble everything ...,162.7442,/xsiecCxd8lkcAluw0wWwbW5CwSv.jpg,2026-05-15,False,Dutton Ranch,9.400,268
2,False,/52sp0vPhLOWrZ1QoZIWiapronM.jpg,[18],273240,[US],en,Off Campus,Hannah Wells tutors hockey captain Garrett Gra...,359.1916,/cbODFqkcmRgrYH8NkG4Q4Hcg8Z1.jpg,2026-05-13,False,Off Campus,8.990,456
3,False,/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg,"[18, 80]",1396,[US],en,Breaking Bad,"Walter White, a New Mexico chemistry teacher, ...",140.8924,/3xnWaLQjelJDDF7LT1WBo6f4BRe.jpg,2008-01-20,False,Breaking Bad,8.947,17922
4,False,/rBOnrVlck7BIlGeWVlzYiZeg4l2.jpg,"[16, 10759, 18, 10765]",209867,[JP],ja,葬送のフリーレン,After the party of heroes defeated the Demon K...,68.8367,/dqZENchTd7lp5zht7BdlqM7RBhD.jpg,2023-09-29,False,Frieren: Beyond Journey's End,8.803,847
5,False,/sZH7lGs06skRKkrqp1LRi57VVMb.jpg,[35],64010,[KR],ko,응답하라 1988,Take a nostalgic trip back to the late 1980s t...,14.4941,/i3xQJlQRff4k5IMEY55l4iKaKl3.jpg,2015-11-06,False,Reply 1988,8.759,214
6,False,/7oBGhqJIghRBvOwo5Qe0yM0cnMc.jpg,"[16, 10759, 10765]",246,[US],en,Avatar: The Last Airbender,"In a war-torn world of elemental magic, a youn...",21.6832,/9RQhVb3r3mCMqYVhLoCu4EvuipP.jpg,2005-02-21,False,Avatar: The Last Airbender,8.800,4873
7,False,/q8eejQcg1bAqImEV8jh8RtBD4uH.jpg,"[16, 10759, 10765]",94605,[US],en,Arcane,Amid the stark discord of twin cities Piltover...,31.3915,/abf8tHznhSvl9BAElD2cQeRr7do.jpg,2021-11-06,False,Arcane,8.752,5934
8,False,/7Sgo1XdCrIpJpiNsTPMi9vwKSuC.jpg,[18],250307,[US],en,The Pitt,The staff of Pittsburgh's Trauma Medical Cente...,53.3731,/kvFSpESyBZMjaeOJDx7RS3P1jey.jpg,2025-01-09,False,The Pitt,8.744,782
9,False,/mwczMJeoQrsPERcyP1e900jo3Jv.jpg,[18],219246,[KR],ko,폭싹 속았수다,"In Jeju, a spirited girl and a steadfast boy's...",26.4692,/1VC3sEFxYXYDqQUCAnvWfUsYg1s.jpg,2025-03-07,False,When Life Gives You Tangerines,8.700,534
10,False,/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg,"[10759, 35, 16]",37854,[JP],ja,ワンピース,"Years ago, the fearsome Pirate King, Gol D. Ro...",46.6875,/dB4EDhre2dsC2kxYDavyKWqLQwi.jpg,1999-10-20,False,One Piece,8.738,5350
11,False,/3siv3RaQrdr2tQiv9jHq71sLlzo.jpg,"[10759, 10751, 18]",85077,[US],en,The Chosen,The life of Christ through the eyes of those w...,41.5845,/dqVUFuNrMFWt7uGNWlpo91VKYOI.jpg,2019-04-21,False,The Chosen,8.738,894
12,False,/QbRbCULZVBcrN2uydpmIOQLV5O.jpg,[18],301507,[CA],en,Heated Rivalry,Two of the biggest stars in Major League Hocke...,19.7786,/3YCKbtAkYWCMDLHvkUjGhG7eWoS.jpg,2025-11-28,False,Heated Rivalry,8.729,504
13,False,/3URK0z9PzpVNJrGE7XOuyy6KFzk.jpg,[18],87108,[US],en,Chernobyl,The true story of one of the worst man-made ca...,26.4686,/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg,2019-05-06,False,Chernobyl,8.714,7931
14,False,/2UG177tWHy7xRmMKWJHB7nAUmKd.jpg,"[16, 10759, 10765, 18]",31911,[JP],ja,鋼の錬金術師 FULLMETAL ALCHEMIST,Disregard for alchemy’s laws ripped half of Ed...,45.4275,/5ZFUEOULaVml7pQuXxhpR2SmVUw.jpg,2009-04-05,False,Fullmetal Alchemist: Brotherhood,8.710,2469
15,False,/og2jKploGHYnCz68vV1nRSEE0xV.jpg,"[80, 18]",60059,[US],en,Better Call Saul,Six years before Saul Goodman meets Walter Whi...,81.0712,/zjg4jpK1Wp2kiRvtt5ND0kznako.jpg,2015-02-08,False,Better Call Saul,8.700,6538
16,False,/q5mJ4oKfGc6Cr9reIHFzD0pQzre.jpg,"[10759, 18]",200709,[KR],ko,약한영웅,"With the aid of unexpected friends, a gifted b...",82.8230,/5Sd01WeraL2oA3Vv6O4rcRxockn.jpg,2022-11-18,False,Weak Hero,8.699,448
17,False,/9In9QgVJx7PlFOAgVHCKKSbo605.jpg,"[16, 35, 10765, 10759]",60625,[US],en,Rick and Morty,Follows a sociopathic genius scientist who dra...,162.7050,/owhkU6KRqdXoUQpjV8uyZGPtX58.jpg,2013-12-02,False,Rick and Morty,8.700,10974
18,False,/rqbCbjB19amtOtFQbb3K2lgm2zv.jpg,"[16, 10765, 10759]",1429,[JP],ja,進撃の巨人,"100 years ago, the last remnants of humanity w...",36.6622,/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg,2013-04-07,False,Attack on Titan,8.700,7449
19,False,/lNpkvX2s8LGB0mjGODMT4o6Up7j.jpg,"[80, 18]",1398,[US],en,The Sopranos,The story of New Jersey-based Italian-American...,83.5159,/rTc7ZXdroqjkKivFPvCPX0Ru7uw.jpg,1999-01-10,False,The Sopranos,8.700,3489

# generate those columns we need

In [19]:
 pd.DataFrame(response.json()['results'])[['id', 'name','overview', 'first_air_date', 'popularity', 'vote_average', 'vote_count']]

,id,name,overview,first_air_date,popularity,vote_average,vote_count
0,276161,Teach You a Lesson,"When respect collapses in schools, unconventio...",2026-06-05,295.0964,9.445,292
1,299167,Dutton Ranch,Rip Wheeler and Beth Dutton gamble everything ...,2026-05-15,162.7442,9.400,268
2,273240,Off Campus,Hannah Wells tutors hockey captain Garrett Gra...,2026-05-13,359.1916,8.990,456
3,1396,Breaking Bad,"Walter White, a New Mexico chemistry teacher, ...",2008-01-20,140.8924,8.947,17922
4,209867,Frieren: Beyond Journey's End,After the party of heroes defeated the Demon K...,2023-09-29,68.8367,8.803,847
5,64010,Reply 1988,Take a nostalgic trip back to the late 1980s t...,2015-11-06,14.4941,8.759,214
6,246,Avatar: The Last Airbender,"In a war-torn world of elemental magic, a youn...",2005-02-21,21.6832,8.800,4873
7,94605,Arcane,Amid the stark discord of twin cities Piltover...,2021-11-06,31.3915,8.752,5934
8,250307,The Pitt,The staff of Pittsburgh's Trauma Medical Cente...,2025-01-09,53.3731,8.744,782
9,219246,When Life Gives You Tangerines,"In Jeju, a spirited girl and a steadfast boy's...",2025-03-07,26.4692,8.700,534
10,37854,One Piece,"Years ago, the fearsome Pirate King, Gol D. Ro...",1999-10-20,46.6875,8.738,5350
11,85077,The Chosen,The life of Christ through the eyes of those w...,2019-04-21,41.5845,8.738,894
12,301507,Heated Rivalry,Two of the biggest stars in Major League Hocke...,2025-11-28,19.7786,8.729,504
13,87108,Chernobyl,The true story of one of the worst man-made ca...,2019-05-06,26.4686,8.714,7931
14,31911,Fullmetal Alchemist: Brotherhood,Disregard for alchemy’s laws ripped half of Ed...,2009-04-05,45.4275,8.710,2469
15,60059,Better Call Saul,Six years before Saul Goodman meets Walter Whi...,2015-02-08,81.0712,8.700,6538
16,200709,Weak Hero,"With the aid of unexpected friends, a gifted b...",2022-11-18,82.8230,8.699,448
17,60625,Rick and Morty,Follows a sociopathic genius scientist who dra...,2013-12-02,162.7050,8.700,10974
18,1429,Attack on Titan,"100 years ago, the last remnants of humanity w...",2013-04-07,36.6622,8.700,7449
19,1398,The Sopranos,The story of New Jersey-based Italian-American...,1999-01-10,83.5159,8.700,3489

In [20]:
df = pd.DataFrame(response.json()['results'])[['id', 'name','overview', 'first_air_date', 'popularity', 'vote_average', 'vote_count']]

In [17]:
df.head()

,id,name,overview,first_air_date,popularity,vote_average,vote_count
0,276161,Teach You a Lesson,"When respect collapses in schools, unconventio...",2026-06-05,295.0964,9.445,292
1,299167,Dutton Ranch,Rip Wheeler and Beth Dutton gamble everything ...,2026-05-15,162.7442,9.400,268
2,273240,Off Campus,Hannah Wells tutors hockey captain Garrett Gra...,2026-05-13,359.1916,8.990,456
3,1396,Breaking Bad,"Walter White, a New Mexico chemistry teacher, ...",2008-01-20,140.8924,8.947,17922
4,209867,Frieren: Beyond Journey's End,After the party of heroes defeated the Demon K...,2023-09-29,68.8367,8.803,847

# **Making Empty Date Frame**

In [21]:
df = pd.DataFrame()

In [26]:
for i in range(1,124):
  response = requests.get('https://api.themoviedb.org/3/tv/top_rated?api_key=9b473644c9294c3a7186c778c83440c7&language=en-US&page={}'.format(i))
  temp_df = pd.DataFrame(response.json()['results'])[['id', 'name','overview', 'first_air_date', 'popularity', 'vote_average', 'vote_count']]
  df = pd.concat([df, temp_df], ignore_index=True)

In [27]:
df

,id,name,overview,first_air_date,popularity,vote_average,vote_count
0,276161,Teach You a Lesson,"When respect collapses in schools, unconventio...",2026-06-05,295.0964,9.445,292
1,299167,Dutton Ranch,Rip Wheeler and Beth Dutton gamble everything ...,2026-05-15,162.7442,9.400,268
2,273240,Off Campus,Hannah Wells tutors hockey captain Garrett Gra...,2026-05-13,359.1916,8.990,456
3,1396,Breaking Bad,"Walter White, a New Mexico chemistry teacher, ...",2008-01-20,140.8924,8.947,17922
4,209867,Frieren: Beyond Journey's End,After the party of heroes defeated the Demon K...,2023-09-29,68.8367,8.803,847
...,...,...,...,...,...,...,...
2455,114471,Ironheart,After the events of Black Panther: Wakanda For...,2025-06-24,7.6162,5.318,456
2456,130392,The D'Amelio Show,From relative obscurity and a seemingly normal...,2021-09-03,2.6283,5.002,685
2457,10160,Big Brother,American version of the reality game show whic...,2000-07-05,27.6817,4.900,262
2458,1871,EastEnders,The everyday lives of working-class residents ...,1985-02-19,47.4601,4.241,227
2459,126725,Velma,Jinkies! This raucous reimagining of the Scoob...,2023-01-12,8.9017,3.472,345

## **Convert these data into csv file**

In [28]:
df.to_csv('Top_Rated_TV_Shows.csv')