<a href="https://colab.research.google.com/github/kaushal4445/AI-ML/blob/main/working_with_CSV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [86]:
df = pd.read_csv('train.csv');
df.head()

,id,Sex,Length,Diameter,Height,Whole weight,Whole weight.1,Whole weight.2,Shell weight,Rings
0,0,F,0.550,0.430,0.150,0.7715,0.3285,0.1465,0.2400,11
1,1,F,0.630,0.490,0.145,1.1300,0.4580,0.2765,0.3200,11
2,2,I,0.160,0.110,0.025,0.0210,0.0055,0.0030,0.0050,6
3,3,M,0.595,0.475,0.150,0.9145,0.3755,0.2055,0.2500,10
4,4,I,0.555,0.425,0.130,0.7820,0.3695,0.1600,0.1975,9

In [ ]:
# Index_col Prarmeter

In [88]:
df = pd.read_csv('train.csv', index_col = 'id');
df.head()

,Sex,Length,Diameter,Height,Whole weight,Whole weight.1,Whole weight.2,Shell weight,Rings
id,,,,,,,,,
0,F,0.550,0.430,0.150,0.7715,0.3285,0.1465,0.2400,11
1,F,0.630,0.490,0.145,1.1300,0.4580,0.2765,0.3200,11
2,I,0.160,0.110,0.025,0.0210,0.0055,0.0030,0.0050,6
3,M,0.595,0.475,0.150,0.9145,0.3755,0.2055,0.2500,10
4,I,0.555,0.425,0.130,0.7820,0.3695,0.1600,0.1975,9

In [10]:
import pandas as pd
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"

headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"
}

req = requests.get(url, headers=headers)

data = StringIO(req.text)

df = pd.read_csv(data)

print(df.head())

    Country  Region
0   Algeria  AFRICA
1    Angola  AFRICA
2     Benin  AFRICA
3  Botswana  AFRICA
4   Burkina  AFRICA

In [11]:
pd.read_csv('movie_titles_metadata.tsv')

    m0\t10 things i hate about you\t1999\t6.90\t62847\t['comedy' 'romance']
0    m1\t1492: conquest of paradise\t1992\t6.20\t10...
1    m2\t15 minutes\t2001\t6.10\t25854\t['action' '...
2    m3\t2001: a space odyssey\t1968\t8.40\t163227\...
3    m4\t48 hrs.\t1982\t6.90\t22289\t['action' 'com...
4    m5\tthe fifth element\t1997\t7.50\t133756\t['a...
..                                                 ...
611  m612\twatchmen\t2009\t7.80\t135229\t['action' ...
612  m613\txxx\t2002\t5.60\t53505\t['action' 'adven...
613  m614\tx-men\t2000\t7.40\t122149\t['action' 'sc...
614  m615\tyoung frankenstein\t1974\t8.00\t57618\t[...
615  m616\tzulu dawn\t1979\t6.40\t1911\t['action' '...

[616 rows x 1 columns]

In [54]:
pd.read_csv('movie_titles_metadata.tsv', sep = '\t')

,m0,10 things i hate about you,1999,6.90,62847,['comedy' 'romance']
0,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
1,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
2,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
3,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
4,m5,the fifth element,1997,7.5,133756.0,['action' 'adventure' 'romance' 'sci-fi' 'thri...
...,...,...,...,...,...,...
611,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
612,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
613,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
614,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
615,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

In [ ]:
# SSEP PARAMETRE

In [102]:
pd.read_csv('movie_titles_metadata.tsv', sep = '\t', names=['SRNO', 'MovieName', 'Realaeasing Date', 'Rating', 'Geners'])

,SRNO,MovieName,Realaeasing Date,Rating,Geners
m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
...,...,...,...,...,...
m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

In [ ]:
# header paramter

In [77]:
pd.read_csv('test.csv', header =1)

,0,0.2,1,8,1.1,0.4,0.7,1.2,0.9,0.10,...,1.12,1.13,1.14,12.1,0.19,1.15,1.16,0.20,0.21,1.17
0,1,4,2,5,1,0,0,0,0,1,...,2.0,0.0,3.0,10.0,0.0,0.0,1.0,1.0,0.0,1.0
1,2,5,1,3,0,0,0,0,0,1,...,4.0,0.0,2.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,0,1,6,0,0,1,0,0,0,...,5.0,1.0,0.0,5.0,1.0,0.0,1.0,0.0,0.0,0.0
3,4,5,1,7,0,0,0,0,0,1,...,4.0,0.0,0.0,4.0,0.0,1.0,1.0,0.0,0.0,1.0
4,5,0,1,6,0,0,1,0,0,0,...,8.0,1.0,4.0,9.0,1.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27423,45602,4,1,5,1,0,0,0,1,0,...,10.0,0.0,4.0,8.0,0.0,1.0,0.0,0.0,1.0,0.0
27424,45603,3,1,8,0,0,0,0,1,0,...,7.0,1.0,2.0,12.0,0.0,1.0,0.0,1.0,0.0,0.0
27425,45604,2,1,6,1,6,0,1,0,0,...,2.0,1.0,1.0,8.0,0.0,0.0,0.0,0.0,1.0,0.0
27426,45605,1,1,2,1,0,0,1,0,0,...,4.0,2.0,2.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0
27427,45609,5,1,9,1,0,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [91]:
# usecols_paramter

df = pd.read_csv('train.csv', usecols=['id','Sex', 'Height'])
df.head()

   id Sex  Height
0   0   F   0.150
1   1   F   0.145
2   2   I   0.025
3   3   M   0.150
4   4   I   0.130

In [94]:
from typing import Sequence
# Sequence paramters
df = pd.read_csv('train.csv', usecols=['Sex'])
df.head()

  Sex
0   F
1   F
2   I
3   M
4   I

In [95]:
# Skiprows/ Nrows Paramter
df = pd.read_csv('train.csv', skiprows=[1,2])
df.head()

,id,Sex,Length,Diameter,Height,Whole weight,Whole weight.1,Whole weight.2,Shell weight,Rings
0,2,I,0.160,0.110,0.025,0.0210,0.0055,0.0030,0.0050,6
1,3,M,0.595,0.475,0.150,0.9145,0.3755,0.2055,0.2500,10
2,4,I,0.555,0.425,0.130,0.7820,0.3695,0.1600,0.1975,9
3,5,F,0.610,0.480,0.170,1.2010,0.5335,0.3135,0.3085,10
4,6,M,0.415,0.325,0.110,0.3315,0.1655,0.0715,0.1300,9

In [97]:
df = pd.read_csv('train.csv', nrows=100)
df.head()

,id,Sex,Length,Diameter,Height,Whole weight,Whole weight.1,Whole weight.2,Shell weight,Rings
0,0,F,0.550,0.430,0.150,0.7715,0.3285,0.1465,0.2400,11
1,1,F,0.630,0.490,0.145,1.1300,0.4580,0.2765,0.3200,11
2,2,I,0.160,0.110,0.025,0.0210,0.0055,0.0030,0.0050,6
3,3,M,0.595,0.475,0.150,0.9145,0.3755,0.2055,0.2500,10
4,4,I,0.555,0.425,0.130,0.7820,0.3695,0.1600,0.1975,9

In [98]:
pd.read_csv('movie_titles_metadata.tsv', nrows = 100)

   m0\t10 things i hate about you\t1999\t6.90\t62847\t['comedy' 'romance']
0   m1\t1492: conquest of paradise\t1992\t6.20\t10...
1   m2\t15 minutes\t2001\t6.10\t25854\t['action' '...
2   m3\t2001: a space odyssey\t1968\t8.40\t163227\...
3   m4\t48 hrs.\t1982\t6.90\t22289\t['action' 'com...
4   m5\tthe fifth element\t1997\t7.50\t133756\t['a...
..                                                ...
95  m96\tinvaders from mars\t1953\t6.40\t2115\t['h...
96  m97\tindependence day\t1996\t6.60\t151698\t['a...
97  m98\tindiana jones and the last crusade\t1989\...
98  m99\tindiana jones and the temple of doom\t198...
99  m100\tinnerspace\t1987\t6.50\t16854\t['action'...

[100 rows x 1 columns]

In [103]:
pd.read_csv('movie_titles_metadata.tsv', sep = '\t', nrows = 100,  names=['SRNO', 'MovieName', 'Realaeasing Date', 'Rating', 'Geners'])

,SRNO,MovieName,Realaeasing Date,Rating,Geners
m0,10 things i hate about you,1999,6.9,62847,['comedy' 'romance']
m1,1492: conquest of paradise,1992,6.2,10421,['adventure' 'biography' 'drama' 'history']
m2,15 minutes,2001,6.1,25854,['action' 'crime' 'drama' 'thriller']
m3,2001: a space odyssey,1968,8.4,163227,['adventure' 'mystery' 'sci-fi']
m4,48 hrs.,1982,6.9,22289,['action' 'comedy' 'crime' 'drama' 'thriller']
...,...,...,...,...,...
m95,i am legend,2007,7.1,156084,['drama' 'sci-fi' 'thriller']
m96,invaders from mars,1953,6.4,2115,['horror' 'sci-fi']
m97,independence day,1996,6.6,151698,['action' 'adventure' 'sci-fi' 'thriller']
m98,indiana jones and the last crusade,1989,8.3,174947,['action' 'adventure' 'thriller' 'action' 'adv...
m99,indiana jones and the temple of doom,1984,7.5,112054,['action' 'adventure']

In [107]:
pd.read_csv('zomato.csv', encoding='latin-1')

ParserError: Error tokenizing data. C error: EOF inside string starting at row 3232

In [ ]:
#skip basd lines
add error_bad_lines = false

In [113]:
# dtype paramters
df = pd.read_csv('train.csv', dtype={'Whole weight' : float })
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90615 entries, 0 to 90614
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              90615 non-null  int64
 1   Sex             90615 non-null  object
 2   Length          90615 non-null  float64
 3   Diameter        90615 non-null  float64
 4   Height          90615 non-null  float64
 5   Whole weight    90615 non-null  float64
 6   Whole weight.1  90615 non-null  float64
 7   Whole weight.2  90615 non-null  float64
 8   Shell weight    90615 non-null  float64
 9   Rings           90615 non-null  int64
dtypes: float64(7), int64(2), object(1)
memory usage: 6.9+ MB

,id,Sex,Length,Diameter,Height,Whole weight,Whole weight.1,Whole weight.2,Shell weight,Rings
0,0,F,0.550,0.430,0.150,0.7715,0.3285,0.1465,0.2400,11
1,1,F,0.630,0.490,0.145,1.1300,0.4580,0.2765,0.3200,11
2,2,I,0.160,0.110,0.025,0.0210,0.0055,0.0030,0.0050,6
3,3,M,0.595,0.475,0.150,0.9145,0.3755,0.2055,0.2500,10
4,4,I,0.555,0.425,0.130,0.7820,0.3695,0.1600,0.1975,9

In [114]:
df = pd.read_csv('train.csv', dtype={'Rings' : float })
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90615 entries, 0 to 90614
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              90615 non-null  int64
 1   Sex             90615 non-null  object
 2   Length          90615 non-null  float64
 3   Diameter        90615 non-null  float64
 4   Height          90615 non-null  float64
 5   Whole weight    90615 non-null  float64
 6   Whole weight.1  90615 non-null  float64
 7   Whole weight.2  90615 non-null  float64
 8   Shell weight    90615 non-null  float64
 9   Rings           90615 non-null  float64
dtypes: float64(8), int64(1), object(1)
memory usage: 6.9+ MB

,id,Sex,Length,Diameter,Height,Whole weight,Whole weight.1,Whole weight.2,Shell weight,Rings
0,0,F,0.550,0.430,0.150,0.7715,0.3285,0.1465,0.2400,11.0
1,1,F,0.630,0.490,0.145,1.1300,0.4580,0.2765,0.3200,11.0
2,2,I,0.160,0.110,0.025,0.0210,0.0055,0.0030,0.0050,6.0
3,3,M,0.595,0.475,0.150,0.9145,0.3755,0.2055,0.2500,10.0
4,4,I,0.555,0.425,0.130,0.7820,0.3695,0.1600,0.1975,9.0

In [115]:
# Handling Dates

pd.read_csv('IPL.csv')

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat
...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat

In [116]:
pd.read_csv('IPL.csv', parse_dates=['date']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    object
 2   date             816 non-null    datetime64[ns]
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
dtypes: datetime64[ns](1), int64(2), object(7)
memory usage: 63.9+ KB

In [117]:
# Convertors

def rename(name):
    if name == "Royal Challengers Bangalore":
        return "RCB"
    else:
        return name

In [118]:
rename("Royal Challengers Bangalore")

'RCB'

In [119]:
pd.read_csv('IPL.csv', converters={'team1' : rename})

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,RCB,Kolkata Knight Riders,Royal Challengers Bangalore,field
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat
...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,RCB,Mumbai Indians,Mumbai Indians,field
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,RCB,Sunrisers Hyderabad,Sunrisers Hyderabad,field
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat

In [ ]:
# NA_ values Parameters

In [120]:
pd.read_csv('train.csv')

,id,Sex,Length,Diameter,Height,Whole weight,Whole weight.1,Whole weight.2,Shell weight,Rings
0,0,F,0.550,0.430,0.150,0.7715,0.3285,0.1465,0.2400,11
1,1,F,0.630,0.490,0.145,1.1300,0.4580,0.2765,0.3200,11
2,2,I,0.160,0.110,0.025,0.0210,0.0055,0.0030,0.0050,6
3,3,M,0.595,0.475,0.150,0.9145,0.3755,0.2055,0.2500,10
4,4,I,0.555,0.425,0.130,0.7820,0.3695,0.1600,0.1975,9
...,...,...,...,...,...,...,...,...,...,...
90610,90610,M,0.335,0.235,0.075,0.1585,0.0685,0.0370,0.0450,6
90611,90611,M,0.555,0.425,0.150,0.8790,0.3865,0.1815,0.2400,9
90612,90612,I,0.435,0.330,0.095,0.3215,0.1510,0.0785,0.0815,6
90613,90613,I,0.345,0.270,0.075,0.2000,0.0980,0.0490,0.0700,6
90614,90614,I,0.425,0.325,0.100,0.3455,0.1525,0.0785,0.1050,8

In [121]:
pd.read_csv('train.csv', na_values=['M'])

,id,Sex,Length,Diameter,Height,Whole weight,Whole weight.1,Whole weight.2,Shell weight,Rings
0,0,F,0.550,0.430,0.150,0.7715,0.3285,0.1465,0.2400,11
1,1,F,0.630,0.490,0.145,1.1300,0.4580,0.2765,0.3200,11
2,2,I,0.160,0.110,0.025,0.0210,0.0055,0.0030,0.0050,6
3,3,NaN,0.595,0.475,0.150,0.9145,0.3755,0.2055,0.2500,10
4,4,I,0.555,0.425,0.130,0.7820,0.3695,0.1600,0.1975,9
...,...,...,...,...,...,...,...,...,...,...
90610,90610,NaN,0.335,0.235,0.075,0.1585,0.0685,0.0370,0.0450,6
90611,90611,NaN,0.555,0.425,0.150,0.8790,0.3865,0.1815,0.2400,9
90612,90612,I,0.435,0.330,0.095,0.3215,0.1510,0.0785,0.0815,6
90613,90613,I,0.345,0.270,0.075,0.2000,0.0980,0.0490,0.0700,6
90614,90614,I,0.425,0.325,0.100,0.3455,0.1525,0.0785,0.1050,8

In [ ]:
#Loading a huge dataset into chunks

In [123]:
dfs = pd.read_csv('train.csv', chunksize=5000)
for chunks in dfs:
  print(chunks.size)

50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
6150